stages:
  - test

test:tox:
  stage: test
  image: python:$PYTHON_VERSIONS
  parallel:
    matrix:
      - PYTHON_VERSIONS:
        - "3.7"
        - "3.8"
        - "3.9"
        - "3.10"
        - "3.11"
  script:
    - python3 -m pip install --upgrade pip wheel tox
    - tox
